package com.starmol.circuitreview.backend.repository.circuitreview;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.starmol.circuitreview.backend.bean.vo.CircuitFileAuditVO;
import com.starmol.circuitreview.backend.constant.CircuitFileAuditSortFieldEnum;
import com.starmol.circuitreview.backend.constant.CircuitReviewResultDetailAuditTypeEnum;
import com.starmol.circuitreview.backend.constant.SortDirectionEnum;
import com.starmol.circuitreview.backend.model.circuitreview.CircuitReviewResultAudit;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * 电路审查结果审核数据访问层
 */
@Mapper
public interface CircuitReviewResultAuditMapper extends BaseMapper<CircuitReviewResultAudit> {
    
    @Select({"<script>",
            "SELECT ",
            "    f.id as fileId, ",
            "    f.file_name as fileName, ",
            "    fv.id as fileVersionId, ",
            "    fv.file_name as fileVersionName, ",
            "    f.secret_level as secretLevel, ",
            "    f.department_id as departmentId, ",
            "    ra.id as resultAuditId, ",
            "    ra.result_id as resultId, ",
            "    ra.is_audit_finished as isAuditFinished, ",
            "    ra.is_admin_audit_finished as isAdminAuditFinished, ",
            "    ra.is_expert_audit_finished as isExpertAuditFinished, ",
            "    ra.audit_time as auditSubmitTime, ",
            "    d.name as departmentName, ",
            "    f.owner_id as ownerId, ",
            "    f.is_recycle as isRecycle, ",
            "    f.compatible_models, ",
            "    f.product_model, ",
            "    f.product_name, ",
            "    f.diagram_number, ",
            "    f.diagram_version, ",
            "    u.name as ownerName ",
            "FROM dlsc_file f ",
            "INNER JOIN (",
            "    SELECT DISTINCT ON (rda.file_id) rda.file_id, rda.result_audit_id ",
            "    FROM dlsc_review_result_detail_audit rda ",
            "    INNER JOIN dlsc_review_result_audit ra_temp ON rda.result_audit_id = ra_temp.id ",
            "    <where> ",
            "        <if test='fileName != null and fileName != \"\"'> ",
            "            AND EXISTS (",
            "                SELECT 1 FROM dlsc_file f_temp WHERE f_temp.id = rda.file_id AND f_temp.file_name LIKE CONCAT('%', #{fileName}, '%')",
            "            ) ",
            "        </if> ",
            "        <if test='auditTypeEnumList != null and auditTypeEnumList.size() > 0'> ",
            "            AND rda.audit_type IN ",
            "            <foreach collection='auditTypeEnumList' item='auditType' open='(' separator=',' close=')'> ",
            "              #{auditType} ",
            "            </foreach> ",
            "        </if> ",
            "    </where> ",
            "    ORDER BY rda.file_id, ra_temp.audit_time DESC NULLS LAST",
            ") unique_files ON f.id = unique_files.file_id ",
            "LEFT JOIN dlsc_review_result_audit ra ON unique_files.result_audit_id = ra.id ",
            "LEFT JOIN dlsc_file_version fv ON ra.file_version_id = fv.id ",
            "LEFT JOIN urm_department d ON f.department_id = d.id ",
            "LEFT JOIN urm_user u ON f.owner_id = u.id ",
            "WHERE f.is_delete = 0 AND ra.is_delete = 0 ",
            "<if test='depId != null'> ",
            "  AND f.department_id = #{depId} ",
            "</if> ",
            "<if test='userId != null'> ",
            "  AND f.owner_id = #{userId} ",
            "</if> ",
            "<if test='status != null and isAdmin == true'> ",
            "  AND ra.is_admin_audit_finished = #{status} ",
            "</if> ",
            "<if test='status != null and isAdmin == false'> ",
            "  AND ra.is_expert_audit_finished = #{status} ",
            "</if> ",
            "<choose>",
            "  <when test='sortField != null'>",
            "    <choose>",
            "      <when test='sortField.name() == \"FILE_NAME\"'>",
            "        ORDER BY f.file_name ",
            "        <if test='sortDirection != null and sortDirection.name() == \"DESC\"'>DESC NULLS LAST</if>",
            "        <if test='sortDirection == null or sortDirection.name() == \"ASC\"'>ASC</if>",
            "      </when>",
            "      <when test='sortField.name() == \"DEPARTMENT_NAME\"'>",
            "        ORDER BY d.name ",
            "        <if test='sortDirection != null and sortDirection.name() == \"DESC\"'>DESC NULLS LAST</if>",
            "        <if test='sortDirection == null or sortDirection.name() == \"ASC\"'>ASC</if>",
            "      </when>",
            "      <when test='sortField.name() == \"OWNER_NAME\"'>",
            "        ORDER BY u.name ",
            "        <if test='sortDirection != null and sortDirection.name() == \"DESC\"'>DESC NULLS LAST</if>",
            "        <if test='sortDirection == null or sortDirection.name() == \"ASC\"'>ASC</if>",
            "      </when>",
            "      <when test='sortField.name() == \"STATUS\"'>",
            "        <choose>",
            "          <when test='isAdmin == true'>",
            "            ORDER BY ra.is_admin_audit_finished ",
            "            <if test='sortDirection != null and sortDirection.name() == \"DESC\"'>DESC NULLS LAST</if>",
            "            <if test='sortDirection == null or sortDirection.name() == \"ASC\"'>ASC</if>",
            "          </when>",
            "          <otherwise>",
            "            ORDER BY ra.is_expert_audit_finished ",
            "            <if test='sortDirection != null and sortDirection.name() == \"DESC\"'>DESC NULLS LAST</if>",
            "            <if test='sortDirection == null or sortDirection.name() == \"ASC\"'>ASC</if>",
            "          </otherwise>",
            "        </choose>",
            "      </when>",
            "      <when test='sortField.name() == \"AUDIT_TIME\"'>",
            "        ORDER BY ra.audit_time ",
            "        <if test='sortDirection != null and sortDirection.name() == \"DESC\"'>DESC NULLS LAST</if>",
            "        <if test='sortDirection == null or sortDirection.name() == \"ASC\"'>ASC</if>",
            "      </when>",
            "      <when test='sortField.name() == \"DIAGRAM_NUMBER\"'>",
            "        ORDER BY f.diagram_number ",
            "        <if test='sortDirection != null and sortDirection.name() == \"DESC\"'>DESC NULLS LAST</if>",
            "        <if test='sortDirection == null or sortDirection.name() == \"ASC\"'>ASC</if>",
            "      </when>",
            "      <when test='sortField.name() == \"FILE_VERSION_NAME\"'>",
            "        ORDER BY fv.file_name ",
            "        <if test='sortDirection != null and sortDirection.name() == \"DESC\"'>DESC NULLS LAST</if>",
            "        <if test='sortDirection == null or sortDirection.name() == \"ASC\"'>ASC</if>",
            "      </when>",
            "      <otherwise>",
            "        ORDER BY ra.audit_time DESC NULLS LAST ",
            "      </otherwise>",
            "    </choose>",
            "  </when>",
            "  <otherwise>",
            "    ORDER BY ra.audit_time DESC NULLS LAST ",
            "  </otherwise>",
            "</choose>",
            "</script>"
    })
    IPage<CircuitFileAuditVO> getCircuitReviewResultAuditVOPage(Page<CircuitFileAuditVO> page,
                                                                String fileName,
                                                                Long depId,
                                                                Long userId,
                                                                Integer status,
                                                                List<CircuitReviewResultDetailAuditTypeEnum> auditTypeEnumList,
                                                                CircuitFileAuditSortFieldEnum sortField,
                                                                SortDirectionEnum sortDirection,
                                                                boolean isAdmin);
}